name: schedule-bot
services:
    db:
        hostname: scheduleBot-db
        image: mysql:8.0.26
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            MYSQL_DATABASE: '${MYSQL_DB}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PW}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_USER_PW}'
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
        networks:
            - scheduleBot-network
        env_file:
            - .env
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 3
    schedulingassistant:
        depends_on:
            db:
                condition: service_healthy
        hostname: scheduleBot-service
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            # Discord Bot configuration
            DISCORD_BOT_TOKEN: '${DISCORD_BOT_TOKEN}'
            DISCORD_EVENT_ROLE_PREFIX: '${DISCORD_EVENT_ROLE_PREFIX}'
            # Database connection
            MYSQL_SERVER: '${MYSQL_SERVER}' # optional (Default: scheduleBot-db)
            MYSQL_DB: '${MYSQL_DB}' # optional (Default: ScheduleBot)
            MYSQL_USER: '${MYSQL_USER}' # optional (Default: scheduleBot)
            MYSQL_USER_PW: '${MYSQL_USER_PW}' # optional (Default: scheduleBot)
            # AWS configuration
            AWS_ACCESS_KEY: '${AWS_ACCESS_KEY}'
            AWS_SECRET_KEY: '${AWS_SECRET_KEY}'
            AWS_REGION: '${AWS_REGION}'
            AWS_BUCKET_NAME: '${AWS_BUCKET_NAME}'
            # API configuration
            ASPNETCORE_URLS: "http://+:80"
            ASPNETCORE_ENVIRONMENT: "Production"
        ports:
            - "5000:80"
        networks:
            - scheduleBot-network
        env_file:
            - .env
volumes:
  db:
    driver: local
networks:
    scheduleBot-network:
        internal: false
        driver: bridge
        name: scheduleBot-network